---
- name: Ping all Tomcat servers by tag
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: ssh
    ansible_user: ritishreddy
    ansible_ssh_pass: "Ritishreddy@20021995"   # or use SSH key
  tasks:
    - name: Ping only VMs tagged as tomcatservers
      ansible.builtin.ping: {}
      when: hostvars[inventory_hostname].get('azure_tags', {}).get('Name') == 'tomcatservers'
